### PR TITLE
Add sleep option to FE entrypoint

### PR DESCRIPTION
**Pull request by MrCreosote**
Useful for debugging configs in Rancher if the service doesn't start

### CODE REVIEW

**Review by Tianhao-Gu — APPROVED** [review]
👍

**Comment by bio-boris** [comment]
The trick is to set the entrypoint to `/bin/sleep` and the cmd to `infinity` so you can put any container to sleep without needing to modify anything. Most containers have /bin/sleep built in

**Comment by bio-boris** [comment]
Then you can call your old entrypoint as usual, since its a bash script, and you can figure out exactly where it crashes and such.

**Comment by MrCreosote** [comment]
The docker compose set up from starrocks had a sleep in the (long) command, so when I converted the image to use envvars I put the sleep in the entry point so it behaved the same way. I just copied the same thing to the fe here. 

Plus it lets you just set an envvar instead of changing the entrypoint and command

**Pull request merged**
